"""EntroTect 动效设计令牌生成器。

把 emil-design-eng 规范的缓动曲线与弹簧参数烘焙为:
  - packages/shared/tokens/motion.css    :root CSS 变量 + 弹簧 @keyframes(GPU 加速)
  - packages/shared/tokens/motion.json  WAAPI 消费的同一份数据

运行时入场动画全部走烘焙产物:零 JS 每帧开销,加载卡顿期依然顺滑;
可中断手势类动画由 renderer 用 WAAPI + CSS transition 实现。
"""

import json
from pathlib import Path

from spring import spring_preset

ROOT = Path(__file__).resolve().parents[2]
TOKENS_DIR = ROOT / "packages" / "shared" / "tokens"

EASINGS = {
    # 强烈 ease-out:UI 出场(进入)反馈,起手快、收尾缓
    "out": "cubic-bezier(0.23, 1, 0.32, 1)",
    # 强烈 ease-in-out:屏幕内移动/变形
    "in-out": "cubic-bezier(0.77, 0, 0.175, 1)",
    # iOS 抽屉曲线(Ionic Framework 来源)
    "drawer": "cubic-bezier(0.32, 0.72, 0, 1)",
}

# UI 动画全部 < 300ms;按钮按压 100-160ms 档
DURATIONS_MS = {
    "press": 140,
    "tooltip": 160,
    "fast": 180,
    "modal": 260,
}

# 弹簧预设(Apple 风格:低 bounce,感知时长全部 < 350ms)
SPRINGS = {
    # 弹窗/卡片入场:scale 0.96→1 + 上浮 + 淡入
    "pop": {"stiffness": 420, "damping": 30, "duration_ms": 300},
    # 消息/列表项入场:轻上浮 + 淡入
    "rise": {"stiffness": 260, "damping": 30, "duration_ms": 340},
    # toast 入场:底部滑入
    "toast": {"stiffness": 300, "damping": 26, "duration_ms": 320},
}

# 每种弹簧烘焙成的视觉属性(起始偏移量)
SPRING_VISUALS = {
    "pop": {"scaleFrom": 0.96, "translateY": 6},
    "rise": {"scaleFrom": 1.0, "translateY": 10},
    "toast": {"scaleFrom": 1.0, "translateY": 14},
}


def keyframe_steps(samples: list[tuple[float, float]]) -> list[tuple[float, float]]:
    """按 2% 步长抽稀采样,保证 CSS 体积小且曲线足够光滑。"""
    by_offset = {round(t, 2): x for t, x in samples}
    return sorted((o, by_offset[o]) for o in by_offset if round(o * 100) % 2 == 0)


def css_keyframes(name: str, preset: dict, visual: dict) -> str:
    steps = keyframe_steps(preset["samples"])
    lines = [f"@keyframes entro-{name}-in {{"]
    for offset, x in steps:
        pct = round(offset * 100)
        opacity = round(min(1.0, x * 1.35), 3)
        scale = round(visual["scaleFrom"] + (1.0 - visual["scaleFrom"]) * x, 4)
        ty = round(visual["translateY"] * (1.0 - x), 2)
        lines.append(
            f"  {pct}% {{ opacity: {opacity}; "
            f"transform: translateY({ty}px) scale({scale}); }}"
        )
    lines.append("}")
    return "\n".join(lines)


def _kebab(name: str) -> str:
    out = []
    for ch in name:
        if ch.isupper():
            out.append("-")
            out.append(ch.lower())
        else:
            out.append(ch)
    return "".join(out)

def css_vars() -> str:
    lines = [":root {"]
    for key, curve in EASINGS.items():
        lines.append(f"  --ease-{key}: {curve};")
    for key, ms in DURATIONS_MS.items():
        lines.append(f"  --dur-{key}: {ms}ms;")
    # 弹簧烘焙时长一并导出,供 CSS animation-duration 引用
    for name, params in SPRINGS.items():
        preset = spring_preset(**params)
        lines.append(f"  --spring-{name}-ms: {preset['durationMs']}ms;")
    lines.append("}")
    return "\n".join(lines)


def reduced_motion_block() -> str:
    return "\n".join([
        "@media (prefers-reduced-motion: reduce) {",
        "  * { animation-duration: 0.01ms !important;",
        "      animation-iteration-count: 1 !important; }",
        "}",
    ])


def build_json() -> dict:
    springs = {}
    for name, params in SPRINGS.items():
        preset = spring_preset(**params)
        steps = keyframe_steps(preset["samples"])
        visual = SPRING_VISUALS[name]
        springs[name] = {
            "stiffness": preset["stiffness"],
            "damping": preset["damping"],
            "mass": preset["mass"],
            "durationMs": preset["durationMs"],
            "keyframes": [
                {
                    "offset": round(offset, 2),
                    "opacity": round(min(1.0, x * 1.35), 3),
                    "transform": (
                        f"translateY({round(visual['translateY'] * (1 - x), 2)}px) "
                        f"scale({round(visual['scaleFrom'] + (1 - visual['scaleFrom']) * x, 4)})"
                    ),
                }
                for offset, x in steps
            ],
        }
    return {"easings": EASINGS, "durationsMs": DURATIONS_MS, "springs": springs}


def main() -> None:
    TOKENS_DIR.mkdir(parents=True, exist_ok=True)

    css_parts = [
        "/* EntroTect motion tokens -- generated by tools/motion/gen_motion.py */",
        css_vars(),
        "",
        *(css_keyframes(name, spring_preset(**params), SPRING_VISUALS[name])
          for name, params in SPRINGS.items()),
        "",
        reduced_motion_block(),
    ]
    (TOKENS_DIR / "motion.css").write_text("\n".join(css_parts) + "\n", encoding="utf-8")

    payload = build_json()
    (TOKENS_DIR / "motion.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    print(f"motion tokens -> {TOKENS_DIR}")
    for name, spring in payload["springs"].items():
        print(f"  spring/{name}: {spring['durationMs']}ms "
              f"(k={spring['stiffness']}, d={spring['damping']})")


if __name__ == "__main__":
    main()
